# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/ for more details
version: 2

references:
  working_directory: /tmp/gh-pages

  load_image: &load_image
    docker:
      - image: circleci/node

  env_vars_test: &env_vars_test
    environment:
      - CIRCLECI: "production"

  env_vars_prod: &env_vars_prod
    environment:
      - CIRCLECI: "production"

  install_dependencies: &install_dependencies
    run:
      name: install-dependencies
      command: |
        make all
        make test

  setup_ssh_gh_pages: &setup_ssh_gh_pages
    add_ssh_keys:
      fingerprints:
        # gh-pages deployment key from circle-ci config
        - 2f:3c:9a:b5:80:16:1f:a2:b9:3f:1c:38:2b:a8:60:9e

  # commit changes to gh-pages
  # [ci skip] has been added to avoid loops with CircleCI triggers
  publish_changes_gh_pages: &publish_changes_gh_pages
    run:
      name: publish_changes_gh_pages
      command: |
        make gh-pages

jobs:
  test:
    <<: *load_image
    <<: *env_vars_test
    steps:
      - checkout
      - <<: *install_dependencies

  build_and_deploy_gh_pages:
    <<: *load_image
    <<: *env_vars_prod
    steps:
      - checkout
      - <<: *install_dependencies
      - <<: *setup_ssh_gh_pages
      - <<: *publish_changes_gh_pages

workflows:
  version: 2
  # For any branch other than master,
  # run CI tests at each commit
  on-commit-test:
    jobs:
      - test:
          filters:
            branches:
              ignore:
                - master
  # For each commit on the master branch
  # deploy to VMs and to gh-pages
  on-commit-build-and-deploy:
    jobs:
      - build_and_deploy_gh_pages:
          filters:
            branches:
              only:
                - master
